### ISSUE TITLE
[BUG] Jet pt ordering

### ISSUE THREAD

**Issue by nshadskiy** [KIT-CMS/CROWN#115]
**Describe the bug**
The algorithm to sort jets by their transverse momentum is working wrong.
https://github.com/KIT-CMS/CROWN/blob/468666c6cee15aef714b03460c3f3e9c0ed25c04/src/jets.hxx#L75-L81
`VecOps::Argsort` is sorting here the indices of the jets with non-zero pt and not the jet pt itself. This leads to a wrong ordering.

**Comment by nshadskiy** [comment]
I made a pull request to fix this problem https://github.com/KIT-CMS/CROWN/pull/116

**Comment by harrypuuter** [comment]
Resolved by #116
