### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ralfschmieder** [KIT-CMS/CROWN#135]
systematics missing in config:
jecUncEC2YearUp
jecUnjecUncEC2YearUpcHFUDown

**Comment by nshadskiy** [comment]
I think this is a copy paste fail jecUn`jecUncEC2YearUp`cHFUp and should be only jecUncEC2YearUp
https://github.com/KIT-CMS/CROWN/blob/638b0f8e834da59eef155596d62acf0e1610abdd/config/config.py#L1139
I will fix this in my current PR https://github.com/KIT-CMS/CROWN/pull/131
Nice catch!

**Comment by nshadskiy** [comment]
Since the PR is now merged I will close this issue.
