### ISSUE TITLE
-DSHIFT not working if shift is only in specific channel

### ISSUE THREAD

**Issue by ralfschmieder** [KIT-CMS/CROWN#143]
https://github.com/KIT-CMS/CROWN/blob/main/code_generation/configuration.py#L607
error if shift is not in all scopes

**Comment by harrypuuter** [comment]
do you have a `cmake` build command to reproduce this issue ?

**Comment by ralfschmieder** [comment]
cmake .. -DANALYSIS=config -DSAMPLES=ggh -DERAS=2018 -DCHANNELS=tt -DSHIFTS=vs
