### ISSUE TITLE
[BUG] Combination of p4 vectors with default float values

### ISSUE THREAD

**Issue by nshadskiy** [KIT-CMS/CROWN#225]
**Describe the bug**
If you define a p4 vector with default values (which are -10., see [here](https://github.com/KIT-CMS/CROWN/blob/14a683494fffcb6b49b1e527e4e48eb725f77cbf/include/defaults.hxx#L11)) you get as expected a vector where all values are outside the common ranges of variables like p_T, eta, phi and so on. 
This happens for example is you search for bb or tautau pairs and don't find any in an event.

But if you combine two of of such default p4 vectors (e.g. with [this](https://github.com/KIT-CMS/CROWN/blob/14a683494fffcb6b49b1e527e4e48eb725f77cbf/include/lorentzvectors.hxx#L32) function) the combined vector has values which are inside a common range.

Example:
```bash
>>> import ROOT as r
>>> v1 = r.Math.PtEtaPhiMVector(-10.,-10.,-10.,-10.)
>>> v2 = r.Math.PtEtaPhiMVector(-10.,-10.,-10.,-10.)
>>> v_comb = v1 + v2
>>> v_comb.Pt()
20.0
>>> v_comb.Eta()
8.422706720630622
>>> v_comb.Phi()
-0.5752220392306208
>>> v_comb.M()
-45492.004396377175
```
p_T and phi have now values that can occur in real events.

This is not be a problem if you cut away all events where you don't find any pairs, but if not this contaminates the distributions with false events.

**Comment by harrypuuter** [comment]
What if we just use 
```c++
const auto default_lorentzvector = ROOT::Math::PtEtaPhiMVector(0,0,0,0);
```

would this break things ?

**Comment by nshadskiy** [comment]
Then the combined vector also has 0 everywhere, so should be fine. 

Otherwise I actually fixed it in my branch by specifically checking the individual p4 vectors before combining them and return the default vector if at least one of them has default values. I just forgot about it.
https://github.com/KIT-CMS/CROWN/blob/2543152ee8b5eaba5aae7bb75176c245901849df/include/lorentzvectors.hxx#L33-L54
I will make a PR for that.

**Comment by harrypuuter** [comment]
thanks !
