### ISSUE TITLE
Pileup Reweighting

### ISSUE THREAD

**Issue by harrypuuter** [KIT-CMS/CROWN#67]
- [x] Readout weights
- [ ] simple config for calculating the weights

**Comment by swozniewski** [comment]
`simple config for calculating the weights` probably not needed. Tool should be runnable on nanoAOD directly.

**Comment by harrypuuter** [comment]
should we add the corresponding script to the repository as well ? Or should we keep CROWN clean and start another repository, containing helper script and the steering stuff like batch submission etc ?

**Comment by swozniewski** [comment]
I think I'd keep CROWN clean for now. If we feel one day that KITHiggs is too deprecated we can still move scripts from there.
