### ISSUE TITLE
Add Metadata to the generated samples

### ISSUE THREAD

**Issue by harrypuuter** [KIT-CMS/CROWN#73]
Adding some metadata to the sample should help in further processing the samples and will make reproducibility of the samples easier

Some ideas which metadata could be useful

- [ ] List of all shifts considered in the ntuple
- [ ] List of all variable names (although this is maybe too much)
- [ ] current framework commit hash
- [ ] is the current repository clean
- [ ] cmake options used (currently this would be era, sample, config)

**Comment by swozniewski** [comment]
sounds good! A list of variable names should not be too much. In fact, I think we had already envisaged it at some point in order to easy the usage since TTree::Print will dump a  huge list with all variations.

**Comment by harrypuuter** [comment]
Yes, the main motivation was, that when we have to further process the ntuples, we can use the information of all shifts to make all following steps a bit easier and avoid e.g. checking all leaves in a tree

**Comment by swozniewski** [comment]
https://root-forum.cern.ch/t/meta-data-in-root-files/16490

**Comment by swozniewski** [comment]
addressed by #86 and #87
