### ISSUE TITLE
Running the Framework

### ISSUE THREAD

**Issue by felix-phy** [KIT-CMS/CROWN#77]
When running the compiled program, the appropriate flags to use are not clear for the input / output. currently the error message reads ```Require exactly two additional input arguments (the input and output paths to the ROOT files) but got 0``` - a `help` message along the lines of ```list of required flags: --input: *description* --output: *description* --otherflags?: *description*``` would be useful

**Comment by harrypuuter** [comment]
but that is not correct, you dont need any flags, just two arguments

**Comment by harrypuuter** [comment]
which is what the error message also states
